{% set name = "azure-mgmt-core" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-mgmt-core-{{ version }}.zip
  sha256: d195208340094f98e5a6661b781cde6f6a051e79ce317caabd8ff97030a9b3ae

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - azure-core<2.0.0,>=1.26.2

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.core

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE.md
  summary: Microsoft Azure Management Core Library for Python.
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-mgmt-core

extra:
  recipe-maintainers:
    - tim-werner
    - xylar
