{% set name = "azure-mgmt-core" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 4246810996107f72482a9351cf918d380c257e90942144ec9c0c2abda1d0a312

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - azure-core <2.0.0,>=1.8.2

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.core

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Microsoft Azure Management Core Library for Python.

extra:
  recipe-maintainers:
    - tim-werner
